### ISSUE TITLE
Game Timer

### ISSUE THREAD

**Issue by Visheshk** [CPL-UW/pdcny_tradewars#11]
Server functionality, and admin abilities to set timers for game. Maybe if timer runs out, trades stop working.

**Comment by Visheshk** [comment]
Year functionality built in.
@mberland : Do we want to build in functionality to pause the game as well?

**Comment by mberland** [comment]
definitely! and, if possible, force a transition to the next year

**Comment by Visheshk** [comment]
Data level ability to pause and skip built in! Yet to make the corresponding front end for that

**Comment by miketissenbaum** [comment]
Pause is a great idea! I assume these are all things baked into the admin
side of things. I think we should think about the admin app some more -
let's work on how that should look (even just a messy sketch like what
we've done for the other screens).
