### ISSUE TITLE
History graph of prices

### ISSUE THREAD

**Issue by Visheshk** [CPL-UW/pdcny_tradewars#5]
In the individual players' game views, they should be able to select individual resources and see graphs of the prices they've gone through.

**Comment by Visheshk** [comment]
I personally don't think this is very game-like, or useful in terms of fun or something a typical player would want to engage with. Alternate to this, figure out a more organic way to enable figuring out trends regarding price changes of resources? Ideally wrap it in the running narrative of events well, I'd imagine

**Comment by mberland** [comment]
Personally, I think ppl would like to know price histories... Not very
game-like, I suppose, though, yes.

**Comment by miketissenbaum** [comment]
How about something about their own profits/losses?

**Comment by Visheshk** [comment]
One graph exists, right now tracking gold. Need to make it so that users can choose which stock they want to see graphs of.

**Comment by mberland** [comment]
It’s set up so you can overlay multiple lines on the same graph. (Just put them in the array. Make sure the array ONLY contains things you want to graph unless I MAKE MORE CODE.) Lemme know if you need to d3 some stuff!

Matthew

**Comment by Visheshk** [comment]
Not managed to get overlaid lines. (complicated interactions and all? Do we really want that)
But people can click on different items and see their graphs now!

**Comment by systemslim** [comment]
is this about tradewars 2002 the old BBS Door game? cause I play it and been getting bothered a lot lately regarding crypto currency.  I know all about the game so i logged in here and found this.  please let me know if thats the game you are talking about.
