### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by Visheshk** [CPL-UW/pdcny_tradewars#8]
The backend interface, the economics/randomness math, as well as front end interface, to make events happen: that destroy some resource, or make it high demand thus high price, or excess supply, or just price drop because it isn't used any more (all markets developed such and such technology, that makes this resource useless for now).

**Comment by mberland** [comment]
Events now randomized by group by year. End-game points are calculated by year-end placement (say, 4 pts for 1st, 3 pts for 2nd, etc.)... Cash is year by year conditional on events.

Events are, to start: 
- Single cheap good x10 ("is really cool right now")
- Single cheap good /10 ("is poisonous this year")

**Comment by Visheshk** [comment]
Yearly events of making expensive a cool resource, and cheaper a poisoned resource now happens in the backend! The group peeps need to be informed on the front end of the chosen resources.
